# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

### actuator properties

management:  endpoints:    web:      exposure:        include: "*"

### logging properties

logging:
  level:
    org.springframework: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE
  pattern: 
    console: "%d{yyyy-MM-dd} %d{HH:mm:ss.SSS} | %blue(%thread) | %5p | %logger | %m%n"